// Edit these lists to customize the wheels. No rebuild needed.
window.VP_DATA = {
  difficulties: [
    { id: "street", name: "Street Kid", bonuses: 0, tag: "EASY" },
    { id: "nomad", name: "Nomad", bonuses: 1, tag: "+1 BONUS" },
    { id: "corpo", name: "Corpo", bonuses: 2, tag: "+2 BONUS" },
    { id: "legend", name: "Legend", bonuses: 3, tag: "+3 BONUS" }
  ],

  fixers: [
    { id: "wakako", name: "Wakako Okada", quote: "No selfies. I want a shot that smells like danger.", image: "img/fixers/wakako.webp" },
    { id: "regina", name: "Regina Jones", quote: "Show me the street. Not a corpo postcard.", image: "img/fixers/regina.webp" },
    { id: "padre", name: "Sebastian \"Padre\" Ibarra", quote: "Dignity. Even in the mud of Heywood.", image: "img/fixers/padre.webp" },
    { id: "hands", name: "Mr. Hands", quote: "Elegance. Precision. Dogtown doesn't do sloppy.", image: "img/fixers/hands.webp" },
    { id: "rogue", name: "Rogue Amendiares", quote: "One gig, one frame. Make it count.", image: "img/fixers/rogue.webp" },
    { id: "dakota", name: "Dakota Smith", quote: "The Badlands don't need filters. Just truth.", image: "img/fixers/dakota.webp" },
    { id: "dino", name: "Dino Dinovic", quote: "Give them a show. Night City eats that up.", image: "img/fixers/dino.webp" },
    { id: "reyes", name: "Muamar \"El Capitán\" Reyes", quote: "Move. Frame. Don't get burned.", image: "img/fixers/reyes.webp" }
  ],

  targets: [
    { id: "v-corpo", label: "V — corpo look", short: "V CORPO" },
    { id: "v-street", label: "V — street look", short: "V STREET" },
    { id: "v-nomad", label: "V — nomad look", short: "V NOMAD" },
    { id: "johnny", label: "Johnny Silverhand", short: "JOHNNY" },
    { id: "judy", label: "Judy Alvarez", short: "JUDY" },
    { id: "panam", label: "Panam Palmer", short: "PANAM" },
    { id: "kerry", label: "Kerry Eurodyne", short: "KERRY" },
    { id: "river", label: "River Ward", short: "RIVER" },
    { id: "jackie", label: "Jackie Welles", short: "JACKIE" },
    { id: "rogue", label: "Rogue Amendiares", short: "ROGUE" },
    { id: "takemura", label: "Goro Takemura", short: "TAKEMURA" },
    { id: "songbird", label: "Song So Mi (Songbird)", short: "SONGBIRD" },
    { id: "reed", label: "Solomon Reed", short: "REED" },
    { id: "alex", label: "Alex (Phantom Liberty)", short: "ALEX" },
    { id: "wakako", label: "Wakako Okada", short: "WAKAKO" },
    { id: "claire", label: "Claire Russell", short: "CLAIRE" },
    { id: "vik", label: "Viktor Vektor", short: "VIK" },
    { id: "misty", label: "Misty Olszewski", short: "MISTY" },
    { id: "smasher", label: "Adam Smasher", short: "SMASHER" },
    { id: "hanako", label: "Hanako Arasaka", short: "HANAKO" },
    { id: "lizzy", label: "Lizzy Wizzy", short: "LIZZY" },
    { id: "alt", label: "Alt Cunningham", short: "ALT" },
    { id: "evelyn", label: "Evelyn Parker", short: "EVELYN" },
    { id: "tbug", label: "T-Bug", short: "T-BUG" },
    { id: "bugbear", label: "8ug8ear", short: "8UG8EAR" },
    { id: "meredith", label: "Meredith Stout", short: "STOUT" },
    { id: "myers", label: "Rosalind Myers", short: "MYERS" },
    { id: "rita", label: "Rita Wheeler", short: "RITA" },
    { id: "dex", label: "Dexter DeShawn", short: "DEX" },
    { id: "dumdum", label: "Dum Dum", short: "DUM DUM" },
    { id: "royce", label: "Royce", short: "ROYCE" },
    { id: "ozob", label: "Ozob Bozo", short: "OZOB" },
    { id: "bluemoon", label: "Blue Moon", short: "BLUE MOON" },
    { id: "redmenace", label: "Red Menace", short: "MENACE" },
    { id: "purpleforce", label: "Purple Force", short: "PURPLE" },
    { id: "aurore", label: "Aurore Cassel", short: "AURORE" },
    { id: "aymeric", label: "Aymeric Cassel", short: "AYMERIC" },
    { id: "cheri", label: "Cheri Nowlin", short: "CHERI" },
    { id: "rachel", label: "Rachel Casich", short: "RACHEL" },
    { id: "lina", label: "Lina Malina", short: "LINA" },
    { id: "regina", label: "Regina Jones", short: "REGINA" },
    { id: "dakota-t", label: "Dakota Smith", short: "DAKOTA" },
    { id: "dino", label: "Dino Dinovic", short: "DINO" },
    { id: "padre", label: "Sebastian \"Padre\" Ibarra", short: "PADRE" },
    { id: "reyes-t", label: "Muamar \"El Capitán\" Reyes", short: "CAPITAN" },
    { id: "garry", label: "Garry the Prophet", short: "GARRY" },
    { id: "hands", label: "Mr. Hands", short: "HANDS" },
    { id: "hansen", label: "Kurt Hansen", short: "HANSEN" },
    { id: "brendan", label: "Brendan the vending machine", short: "BRENDAN" },
    { id: "iguana", label: "The iguana", short: "IGUANA" },
    { id: "nibbles", label: "Nibbles", short: "NIBBLES" },
    { id: "corpo", label: "An unnamed Arasaka corpo", short: "CORPO" },
    { id: "maelstrom", label: "A Maelstrom ganger", short: "MAELSTROM" },
    { id: "tyger", label: "A Tyger Claw", short: "TYGER" },
    { id: "valentino", label: "A Valentino", short: "VALENTINO" },
    { id: "aldecaldo", label: "An Aldecaldo nomad", short: "ALDECALDO" },
    { id: "netrunner", label: "A street netrunner", short: "NETRUNNER" },
    { id: "maxtac", label: "A MaxTac officer", short: "MAXTAC" },
    { id: "scav", label: "A Scavenger", short: "SCAV" },
    { id: "npc", label: "A nameless street NPC", short: "NPC" },
    { id: "arch", label: "An Arch Nazaré", short: "ARCH" },
    { id: "quadra", label: "A Quadra", short: "QUADRA" },
    { id: "av", label: "An AV / aerodyne", short: "AV" },
    { id: "neon", label: "A neon sign", short: "NEON" },
    { id: "apt", label: "V's apartment", short: "APT" },
    { id: "rooftop", label: "A Night City rooftop", short: "ROOFTOP" },
    { id: "terminal", label: "A terminal / interface", short: "JACK IN" },
    { id: "weapon", label: "An iconic weapon", short: "WEAPON" },
    { id: "afterlife", label: "The Afterlife", short: "AFTERLIFE" }
  ],

  shots: [
    { id: "closeup", label: "Tight close-up", short: "CLOSE-UP" },
    { id: "ecu", label: "Extreme close-up / detail", short: "ECU" },
    { id: "cowboy", label: "Medium / cowboy", short: "COWBOY" },
    { id: "full", label: "Full body", short: "FULL" },
    { id: "tiny", label: "Subject tiny in frame", short: "TINY" },
    { id: "low", label: "Low angle", short: "LOW" },
    { id: "high", label: "High angle", short: "HIGH" },
    { id: "birds", label: "Bird's eye", short: "BIRD'S EYE" },
    { id: "worms", label: "Worm's eye", short: "WORM'S EYE" },
    { id: "dutch", label: "Dutch angle", short: "DUTCH" },
    { id: "profile", label: "Profile", short: "PROFILE" },
    { id: "facing", label: "Facing the camera", short: "FACING" },
    { id: "behind", label: "From behind", short: "BEHIND" },
    { id: "ots", label: "Over-the-shoulder", short: "OTS" },
    { id: "pov", label: "POV", short: "POV" },
    { id: "silhouette", label: "Silhouette", short: "SILHOUETTE" },
    { id: "reflect", label: "Reflection", short: "REFLECT" },
    { id: "frame", label: "Frame within a frame", short: "FRAME²" },
    { id: "center", label: "Centered symmetry", short: "CENTER" },
    { id: "edge", label: "Subject on the edge", short: "EDGE" },
    { id: "crop", label: "Hard crop", short: "CROP" },
    { id: "block", label: "Foreground obstruction", short: "BLOCK" },
    { id: "two-shot", label: "Two-shot", short: "TWO-SHOT" },
    { id: "insert", label: "Insert / detail shot", short: "INSERT" },
    { id: "negative", label: "Negative space", short: "NEGATIVE" }
  ],

  briefs: [
    { id: "lonely", label: "Loneliness", short: "LONELY" },
    { id: "tender", label: "Tenderness", short: "TENDER" },
    { id: "power", label: "Power", short: "POWER" },
    { id: "vulnerable", label: "Vulnerability", short: "OPEN" },
    { id: "joy", label: "Joy", short: "JOY" },
    { id: "tension", label: "Tension", short: "TENSION" },
    { id: "waiting", label: "Waiting", short: "WAIT" },
    { id: "exhausted", label: "Exhaustion", short: "SPENT" },
    { id: "pride", label: "Pride", short: "PRIDE" },
    { id: "grief", label: "Grief", short: "GRIEF" },
    { id: "desire", label: "Desire", short: "DESIRE" },
    { id: "trust", label: "Trust", short: "TRUST" },
    { id: "distance", label: "Distance", short: "DISTANCE" },
    { id: "quiet", label: "A quiet moment", short: "QUIET" },
    { id: "candid", label: "Candid, unposed", short: "CANDID" },
    { id: "editorial", label: "Fashion editorial", short: "EDITORIAL" },
    { id: "comfort", label: "Comfort", short: "COMFORT" },
    { id: "defiance", label: "Defiance", short: "DEFIANCE" },
    { id: "home", label: "Home", short: "HOME" },
    { id: "escape", label: "Escape", short: "ESCAPE" },
    { id: "melancholy", label: "Melancholy", short: "BLUE" },
    { id: "curiosity", label: "Curiosity", short: "CURIOUS" },
    { id: "street-doc", label: "Street documentary", short: "STREET" },
    { id: "nostalgia", label: "Nostalgia", short: "NOSTALGIA" },
    { id: "romance", label: "Romance", short: "ROMANCE" },
    { id: "friendship", label: "Friendship", short: "FRIENDS" },
    { id: "intimacy", label: "Intimacy", short: "INTIMACY" },
    { id: "belonging", label: "Belonging", short: "BELONG" },
    { id: "play", label: "Playfulness", short: "PLAY" },
    { id: "hope", label: "Hope", short: "HOPE" },
    { id: "fear", label: "Fear", short: "FEAR" },
    { id: "anger", label: "Anger", short: "ANGER" },
    { id: "shame", label: "Shame", short: "SHAME" },
    { id: "relief", label: "Relief", short: "RELIEF" },
    { id: "awe", label: "Awe", short: "AWE" },
    { id: "mystery", label: "Mystery", short: "MYSTERY" },
    { id: "obsession", label: "Obsession", short: "OBSESS" },
    { id: "farewell", label: "Farewell", short: "FAREWELL" },
    { id: "reunion", label: "Reunion", short: "REUNION" },
    { id: "secret", label: "A secret", short: "SECRET" },
    { id: "celebration", label: "Celebration", short: "PARTY" },
    { id: "labor", label: "Labor / work", short: "WORK" },
    { id: "aftermath", label: "Aftermath", short: "AFTER" },
    { id: "innocence", label: "Innocence", short: "INNOCENT" },
    { id: "dream", label: "Dreamlike", short: "DREAM" },
    { id: "surreal", label: "Surreal", short: "SURREAL" },
    { id: "horror", label: "Horror", short: "HORROR" },
    { id: "absurd", label: "Absurd / comedy", short: "ABSURD" },
    { id: "still-life", label: "Still life", short: "STILL LIFE" },
    { id: "env-portrait", label: "Environmental portrait", short: "ENVIRON" },
    { id: "bts", label: "Behind the scenes", short: "BTS" },
    { id: "everyday", label: "Everyday life", short: "EVERYDAY" },
    { id: "opulence", label: "Opulence", short: "OPULENCE" },
    { id: "care", label: "Care", short: "CARE" },
    { id: "restless", label: "Restlessness", short: "RESTLESS" }
  ],

  bonuses: {
    traitement: [
      { id: "bw", label: "Black & white", eddies: 2000 },
      { id: "magenta", label: "Magenta dominant", eddies: 1500 },
      { id: "cyan", label: "Cyan dominant", eddies: 1500 },
      { id: "amber", label: "Amber dominant", eddies: 1500 },
      { id: "vhs", label: "VHS / analog look", eddies: 2500 },
      { id: "grain", label: "Heavy grain, high contrast", eddies: 1800 },
      { id: "teal", label: "Teal & orange cinema", eddies: 1500 },
      { id: "mono-neon", label: "Neon monochrome (one color + black)", eddies: 2800 },
      { id: "bleach", label: "Bleach bypass — metallic contrast", eddies: 2000 },
      { id: "muted", label: "Muted / desaturated", eddies: 1600 },
      { id: "over-sat", label: "Over-saturated neon", eddies: 1800 },
      { id: "faded", label: "Faded print / washed colors", eddies: 1700 },
      { id: "split-tone", label: "Split tone — two colors, shadows vs highlights", eddies: 2200 },
      { id: "infrared", label: "Infrared / false color", eddies: 2500 },
      { id: "toxic", label: "Acid green / toxic", eddies: 1800 },
      { id: "steel", label: "Cool steel", eddies: 1500 },
      { id: "tungsten", label: "Warm tungsten", eddies: 1500 },
      { id: "glitch", label: "Glitch / datamosh", eddies: 2600 },
      { id: "polaroid", label: "Polaroid / instant film", eddies: 1900 }
    ],
    technique: [
      { id: "dof", label: "Razor DOF — one detail sharp", eddies: 2200 },
      { id: "deep-focus", label: "Deep focus — everything sharp", eddies: 1800 },
      { id: "blur", label: "Intentional motion blur", eddies: 2500 },
      { id: "trails", label: "Long exposure — light trails", eddies: 2600 },
      { id: "blown", label: "Blown highlights", eddies: 1600 },
      { id: "crushed", label: "Crushed blacks, deep shadows", eddies: 1600 },
      { id: "under", label: "Underexposed, muddy mids", eddies: 1700 },
      { id: "bloom", label: "Soft bloom / haze", eddies: 1800 },
      { id: "vignette", label: "Heavy vignette", eddies: 1500 },
      { id: "ca", label: "Chromatic aberration", eddies: 1800 },
      { id: "dirty", label: "Dirty or fogged lens", eddies: 2000 },
      { id: "flare", label: "Anamorphic flares", eddies: 1900 },
      { id: "diffusion", label: "Diffusion / pro-mist", eddies: 1700 },
      { id: "handheld", label: "Handheld, imperfect", eddies: 2000 }
    ],
    scene: [
      { id: "rain", label: "Rain mandatory", eddies: 2200 },
      { id: "wet", label: "Wet streets, after the rain", eddies: 1800 },
      { id: "night", label: "Night only", eddies: 1500 },
      { id: "blue-hour", label: "Blue hour", eddies: 2200 },
      { id: "golden", label: "Golden hour / magic hour", eddies: 2500 },
      { id: "noon", label: "Harsh noon sun", eddies: 2000 },
      { id: "fog", label: "Heavy smog / fog", eddies: 2200 },
      { id: "storm", label: "Storm / lightning", eddies: 2800 },
      { id: "smoke", label: "Smoke in the air", eddies: 2000 },
      { id: "dust", label: "Dust or dirt in the air", eddies: 1900 },
      { id: "crowd", label: "Crowd / living background", eddies: 2200 },
      { id: "empty", label: "Empty street, almost no NPCs", eddies: 2000 },
      { id: "neon-mix", label: "Mixed neon + practicals", eddies: 1800 },
      { id: "sirens", label: "Emergency lights / sirens", eddies: 2400 }
    ],
    format: [
      { id: "ratio-45", label: "4:5 portrait", eddies: 1200 },
      { id: "ratio-916", label: "9:16 vertical", eddies: 1500 },
      { id: "ratio-219", label: "21:9 cinema", eddies: 1800 },
      { id: "ratio-11", label: "1:1 square", eddies: 1200 },
      { id: "ratio-169", label: "16:9 landscape", eddies: 1000 }
    ]
  }
};
