// Edit these lists to customize the wheels. No rebuild needed.
window.VP_DATA = {
  difficulties: [
    { id: "street", name: "Street Kid", bonuses: 0, tag: "EASY" },
    { id: "nomad", name: "Nomad", bonuses: 1, tag: "+1 BONUS" },
    { id: "corpo", name: "Corpo", bonuses: 2, tag: "+2 BONUS" },
    { id: "legend", name: "Legend", bonuses: 3, tag: "+3 BONUS" }
  ],

  fixers: [
    { id: "wakako", name: "Wakako Okada", quote: "No selfies. I want a shot that smells like danger.", image: "img/fixers/wakako.webp" },
    { id: "regina", name: "Regina Jones", quote: "Show me the street. Not a corpo postcard.", image: "img/fixers/regina.webp" },
    { id: "padre", name: "Sebastian \"Padre\" Ibarra", quote: "Dignity. Even in the mud of Heywood.", image: "img/fixers/padre.webp" },
    { id: "hands", name: "Mr. Hands", quote: "Elegance. Precision. Dogtown doesn't do sloppy.", image: "img/fixers/hands.webp" },
    { id: "rogue", name: "Rogue Amendiares", quote: "One gig, one frame. Make it count.", image: "img/fixers/rogue.webp" },
    { id: "dakota", name: "Dakota Smith", quote: "The Badlands don't need filters. Just truth.", image: "img/fixers/dakota.webp" },
    { id: "dino", name: "Dino Dinovic", quote: "Give them a show. Night City eats that up.", image: "img/fixers/dino.webp" },
    { id: "reyes", name: "Muamar \"El Capitán\" Reyes", quote: "Move. Frame. Don't get burned.", image: "img/fixers/reyes.webp" }
  ],

  targets: [
    { id: "v-corpo", label: "V — corpo look", short: "V CORPO" },
    { id: "v-street", label: "V — street look", short: "V STREET" },
    { id: "v-nomad", label: "V — nomad look", short: "V NOMAD" },
    { id: "johnny", label: "Johnny Silverhand", short: "JOHNNY" },
    { id: "judy", label: "Judy Alvarez", short: "JUDY" },
    { id: "panam", label: "Panam Palmer", short: "PANAM" },
    { id: "kerry", label: "Kerry Eurodyne", short: "KERRY" },
    { id: "river", label: "River Ward", short: "RIVER" },
    { id: "jackie", label: "Jackie Welles", short: "JACKIE" },
    { id: "rogue", label: "Rogue Amendiares", short: "ROGUE" },
    { id: "takemura", label: "Goro Takemura", short: "TAKEMURA" },
    { id: "songbird", label: "Song So Mi (Songbird)", short: "SONGBIRD" },
    { id: "reed", label: "Solomon Reed", short: "REED" },
    { id: "alex", label: "Alex (Phantom Liberty)", short: "ALEX" },
    { id: "wakako", label: "Wakako Okada", short: "WAKAKO" },
    { id: "claire", label: "Claire Russell", short: "CLAIRE" },
    { id: "vik", label: "Viktor Vektor", short: "VIK" },
    { id: "misty", label: "Misty Olszewski", short: "MISTY" },
    { id: "smasher", label: "Adam Smasher", short: "SMASHER" },
    { id: "hanako", label: "Hanako Arasaka", short: "HANAKO" },
    { id: "lizzy", label: "Lizzy Wizzy", short: "LIZZY" },
    { id: "hands", label: "Mr. Hands", short: "HANDS" },
    { id: "hansen", label: "Kurt Hansen", short: "HANSEN" },
    { id: "nibbles", label: "Nibbles", short: "NIBBLES" },
    { id: "corpo", label: "An unnamed Arasaka corpo", short: "CORPO" },
    { id: "maelstrom", label: "A Maelstrom ganger", short: "MAELSTROM" },
    { id: "tyger", label: "A Tyger Claw", short: "TYGER" },
    { id: "valentino", label: "A Valentino", short: "VALENTINO" },
    { id: "aldecaldo", label: "An Aldecaldo nomad", short: "ALDECALDO" },
    { id: "netrunner", label: "A street netrunner", short: "NETRUNNER" },
    { id: "maxtac", label: "A MaxTac officer", short: "MAXTAC" },
    { id: "scav", label: "A Scavenger", short: "SCAV" },
    { id: "npc", label: "A nameless street NPC", short: "NPC" },
    { id: "arch", label: "An Arch Nazaré", short: "ARCH" },
    { id: "quadra", label: "A Quadra", short: "QUADRA" },
    { id: "av", label: "An AV / aerodyne", short: "AV" },
    { id: "neon", label: "A neon sign", short: "NEON" },
    { id: "apt", label: "V's apartment", short: "APT" },
    { id: "rooftop", label: "A Night City rooftop", short: "ROOFTOP" },
    { id: "terminal", label: "A terminal / interface", short: "JACK IN" },
    { id: "weapon", label: "An iconic weapon", short: "WEAPON" },
    { id: "afterlife", label: "The Afterlife", short: "AFTERLIFE" }
  ],

  shots: [
    { id: "portrait-cam", label: "Eye contact, tight", short: "EYES" },
    { id: "vert-low", label: "Low angle", short: "LOW" },
    { id: "scope-tiny", label: "Subject tiny in frame", short: "TINY" },
    { id: "square-puddle", label: "Puddle / reflection", short: "REFLECT" },
    { id: "wide-skyline", label: "Skyline + one human detail", short: "SKYLINE" },
    { id: "macro", label: "Macro — chrome, hands, gun, UI", short: "MACRO" },
    { id: "silhouette", label: "Silhouette — neon backlight", short: "SILHOUETTE" },
    { id: "ots", label: "Over-the-shoulder — stolen glance", short: "OTS" },
    { id: "dutch", label: "Dutch angle — the world tilts", short: "DUTCH" },
    { id: "cowboy", label: "Cowboy shot — street pose", short: "COWBOY" },
    { id: "profile", label: "Tight profile — three-quarter face", short: "PROFILE" },
    { id: "archi", label: "Architecture, almost no one", short: "ARCHI" },
    { id: "glass", label: "Through glass, fence, or rain", short: "GLASS" },
    { id: "topdown", label: "High angle — rooftop or overpass", short: "HIGH" },
    { id: "frame", label: "Frame within a frame", short: "FRAME²" },
    { id: "motion", label: "Motion — smear, combat, blur", short: "MOTION" },
    { id: "center", label: "Centered symmetry", short: "CENTER" },
    { id: "edge", label: "Subject on the edge", short: "EDGE" },
    { id: "full", label: "Full body — head to toe", short: "FULL" },
    { id: "behind", label: "From behind — walking away", short: "BEHIND" },
    { id: "pov", label: "POV — through their eyes", short: "POV" },
    { id: "crop", label: "Hard crop — cut the frame", short: "CROP" },
    { id: "block", label: "Foreground obstruction", short: "BLOCK" },
    { id: "ground", label: "Ground level — cheek to asphalt", short: "GROUND" }
  ],

  briefs: [
    { id: "ad", label: "A corpo ad that's too perfect", short: "CORPO AD" },
    { id: "afterfire", label: "After the fire, before the silence", short: "AFTER FIRE" },
    { id: "rotten-luxury", label: "Rotten luxury", short: "LUXURY" },
    { id: "intimacy", label: "Intimacy in a hostile world", short: "INTIMACY" },
    { id: "ignore", label: "Night City ignoring you", short: "IGNORE" },
    { id: "2020", label: "2020 nostalgia", short: "2020" },
    { id: "offscreen", label: "Off-screen danger", short: "OFF-SCREEN" },
    { id: "relic", label: "A prayer to the Relic", short: "RELIC" },
    { id: "fake-life", label: "An ad for a life you don't have", short: "FAKE LIFE" },
    { id: "betrayal", label: "A hug, or a betrayal", short: "BETRAYAL" },
    { id: "chrome", label: "Chrome more human than flesh", short: "CHROME" },
    { id: "rooftop-alone", label: "Rooftop solitude", short: "ROOFTOP" },
    { id: "cheap-glory", label: "Cheap glory", short: "GLORY" },
    { id: "faith", label: "Faith in the city", short: "FAITH" },
    { id: "aftergig", label: "The gig is over. The body remembers.", short: "POST-GIG" },
    { id: "watched", label: "Someone is watching you", short: "WATCHED" },
    { id: "owes", label: "The city owes you nothing", short: "OWES YOU" },
    { id: "deal", label: "Love as a transaction", short: "DEAL" },
    { id: "no-hero", label: "You were never the hero", short: "NO HERO" },
    { id: "no-name", label: "A name nobody will remember", short: "NO NAME" },
    { id: "receipt", label: "Sold your soul, kept the receipt", short: "RECEIPT" },
    { id: "armor", label: "Glamour as armor", short: "ARMOR" },
    { id: "lying", label: "The lights are lying", short: "LIES" },
    { id: "standing", label: "Still standing", short: "STANDING" },
    { id: "last-call", label: "Last call before the end", short: "LAST CALL" },
    { id: "the-job", label: "The job was never the job", short: "THE JOB" },
    { id: "debt", label: "Debt with a heartbeat", short: "DEBT" },
    { id: "analog", label: "Analog heart, digital city", short: "ANALOG" },
    { id: "family", label: "Family is a loaded word", short: "FAMILY" },
    { id: "mercy", label: "A small mercy", short: "MERCY" },
    { id: "unclean", label: "Too late to be clean", short: "UNCLEAN" },
    { id: "one-night", label: "Legend for one night", short: "ONE NIGHT" },
    { id: "ghost", label: "Ghost in the passenger seat", short: "GHOST" },
    { id: "kindness", label: "Power dressed as kindness", short: "KINDNESS" }
  ],

  bonuses: {
    traitement: [
      { id: "bw", label: "Black & white", eddies: 2000 },
      { id: "magenta", label: "Magenta dominant", eddies: 1500 },
      { id: "cyan", label: "Cyan dominant", eddies: 1500 },
      { id: "amber", label: "Amber dominant", eddies: 1500 },
      { id: "vhs", label: "VHS / analog look", eddies: 2500 },
      { id: "grain", label: "Heavy grain, high contrast", eddies: 1800 },
      { id: "teal", label: "Teal & orange cinema", eddies: 1500 },
      { id: "mono-neon", label: "Neon monochrome (one color + black)", eddies: 2800 },
      { id: "bleach", label: "Bleach bypass — metallic contrast", eddies: 2000 },
      { id: "muted", label: "Muted / desaturated", eddies: 1600 },
      { id: "over-sat", label: "Over-saturated neon", eddies: 1800 },
      { id: "faded", label: "Faded print / washed colors", eddies: 1700 },
      { id: "split-tone", label: "Split tone — two colors, shadows vs highlights", eddies: 2200 },
      { id: "infrared", label: "Infrared / false color", eddies: 2500 },
      { id: "toxic", label: "Acid green / toxic", eddies: 1800 },
      { id: "steel", label: "Cool steel", eddies: 1500 },
      { id: "tungsten", label: "Warm tungsten", eddies: 1500 },
      { id: "glitch", label: "Glitch / datamosh", eddies: 2600 },
      { id: "polaroid", label: "Polaroid / instant film", eddies: 1900 }
    ],
    technique: [
      { id: "dof", label: "Razor DOF — one detail sharp", eddies: 2200 },
      { id: "deep-focus", label: "Deep focus — everything sharp", eddies: 1800 },
      { id: "blur", label: "Intentional motion blur", eddies: 2500 },
      { id: "trails", label: "Long exposure — light trails", eddies: 2600 },
      { id: "blown", label: "Blown highlights", eddies: 1600 },
      { id: "crushed", label: "Crushed blacks, deep shadows", eddies: 1600 },
      { id: "under", label: "Underexposed, muddy mids", eddies: 1700 },
      { id: "bloom", label: "Soft bloom / haze", eddies: 1800 },
      { id: "vignette", label: "Heavy vignette", eddies: 1500 },
      { id: "ca", label: "Chromatic aberration", eddies: 1800 },
      { id: "dirty", label: "Dirty or fogged lens", eddies: 2000 },
      { id: "flare", label: "Anamorphic flares", eddies: 1900 },
      { id: "diffusion", label: "Diffusion / pro-mist", eddies: 1700 },
      { id: "handheld", label: "Handheld, imperfect", eddies: 2000 }
    ],
    scene: [
      { id: "rain", label: "Rain mandatory", eddies: 2200 },
      { id: "wet", label: "Wet streets, after the rain", eddies: 1800 },
      { id: "night", label: "Night only", eddies: 1500 },
      { id: "blue-hour", label: "Blue hour", eddies: 2200 },
      { id: "golden", label: "Golden hour / magic hour", eddies: 2500 },
      { id: "noon", label: "Harsh noon sun", eddies: 2000 },
      { id: "fog", label: "Heavy smog / fog", eddies: 2200 },
      { id: "storm", label: "Storm / lightning", eddies: 2800 },
      { id: "smoke", label: "Smoke in the air", eddies: 2000 },
      { id: "dust", label: "Dust or dirt in the air", eddies: 1900 },
      { id: "crowd", label: "Crowd / living background", eddies: 2200 },
      { id: "empty", label: "Empty street, almost no NPCs", eddies: 2000 },
      { id: "neon-mix", label: "Mixed neon + practicals", eddies: 1800 },
      { id: "sirens", label: "Emergency lights / sirens", eddies: 2400 }
    ],
    format: [
      { id: "ratio-45", label: "4:5 portrait", eddies: 1200 },
      { id: "ratio-916", label: "9:16 vertical", eddies: 1500 },
      { id: "ratio-219", label: "21:9 cinema", eddies: 1800 },
      { id: "ratio-11", label: "1:1 square", eddies: 1200 },
      { id: "ratio-169", label: "16:9 landscape", eddies: 1000 }
    ]
  }
};
